### ISSUE TITLE
command 'sessions' error.

### ISSUE THREAD

**Issue by PreDraven** [chainreactors/malice-network#15]
the output:
IOM>  » sessions
panic: missing flag value: flag 'all' not registered

goroutine 1 [running]:
github.com/chainreactors/grumble.FlagMap.Bool(0xc00007f800?, {0xc8f013, 0x3})
	/home/echo/go/pkg/mod/github.com/chainreactors/grumble@v0.0.0-20240726161323-5ed71398873f/flagmap.go:73 +0xf7
github.com/chainreactors/malice-network/client/command/sessions.SessionsCmd(0xc0002c4120, 0xc00024ac00)
	/home/echo/malice-network/client/command/sessions/sessions.go:18 +0x47
github.com/chainreactors/malice-network/client/command/sessions.Commands.func2(0xc00024e000?)
	/home/echo/malice-network/client/command/sessions/commands.go:28 +0x17
github.com/chainreactors/grumble.(*App).RunCommand(0xc00024e000, {0xc000048320?, 0x8?, 0xdc2890?})
	/home/echo/go/pkg/mod/github.com/chainreactors/grumble@v0.0.0-20240726161323-5ed71398873f/app.go:327 +0x17b
github.com/chainreactors/grumble.(*App).runShell(0xc00024e000)
	/home/echo/go/pkg/mod/github.com/chainreactors/grumble@v0.0.0-20240726161323-5ed71398873f/app.go:539 +0x4bb
github.com/chainreactors/grumble.(*App).RunWithReadline(0xc00024e000, 0xc00020e018)
	/home/echo/go/pkg/mod/github.com/chainreactors/grumble@v0.0.0-20240726161323-5ed71398873f/app.go:461 +0x565
github.com/chainreactors/grumble.(*App).Run(0xc00024e000)
	/home/echo/go/pkg/mod/github.com/chainreactors/grumble@v0.0.0-20240726161323-5ed71398873f/app.go:345 +0x136
github.com/chainreactors/malice-network/client/console.Start({0xc0003bdf30, 0x2, 0x12b75f8?})
	/home/echo/malice-network/client/console/console.go:70 +0x374
github.com/chainreactors/malice-network/client/cli.StartConsole(...)
	/home/echo/malice-network/client/cli/cmd.go:9
main.main()
	/home/echo/malice-network/client/client.go:23 +0x3f

how can i resolve it?

**Comment by PreDraven** [comment]
update
